update of example
equinor/neqsimmatlab pull request #39
Opened 2021-06-11 19:21 UTC by EvenSol

added direct access to table from fluid (not needed to flash)

2021-06-12 15:16 UTC, asmfstatoil requested changes
Erstatt neqsim.thermo.system.SystemSrkEOS med kall til thermo

2021-06-12 15:16 UTC, asmfstatoil commented on example/testNewLib.m
> +system1 = neqsim.thermo.system.SystemSrkEos(280,10);
Her må du kalle Matlab-funksjon thermo for å lage System. Visst ikkje må pathNeqSim kallast osv.

2021-06-12 15:16 UTC, asmfstatoil commented on example/testNewLib.m
> +system1 = neqsim.thermo.system.SystemSrkEos(280,10);
Også fint om du skriv kva versjonsnummber neqsim-jar har når du oppdaterar

2021-06-15 12:55 UTC, asmfstatoil approved these changes

2021-06-15 21:39 UTC, asmfstatoil commented
Får følgande feilmelding når eg kallar thermo utan ; (dvs. eg slepp feilmeldingane tilbake til command window)

Det er litt buggete

a = thermo
23:35:27.055 [main] ERROR neqsim.thermo.phase.PhaseEos - Failed to solve for molarVolume within the iteration limit.

Java exception occurred:
java.lang.RuntimeException: neqsim.util.exception.IsNaNException

2021-06-15 22:04 UTC, EvenSol commented
ja - har også utfordring med det. Virker som om display() funkjsonen på hvert object blir kalt når man ikke avslutter med kolon

2021-06-15 22:07 UTC, merged